### ISSUE TITLE
vicuna_13b_4bit_TextGen_GPU

### ISSUE THREAD

**Issue by markwsac** [pcrii/Philo-Colab-Collection#1]
I am using `vicuna_13b_4bit_TextGen_GPU` notebook. Thanks for the notebook. It works but I found responses a bit weird on simple prompts. It doesn't look like  vicuna model being applied. Did you also notice this?

Are also these two lines necessary?

```
!wget https://github.com/pcrii/Philo-Colab-Collection/raw/main/llama.json 
!mv llama.json /content/text-generation-webui/characters

```

**Comment by pcrii** [comment]
nope its just a character file i wanted available. i feel like it helps get better results but i think oobabooga is adding characters to the default install.
 the colab is working for you? text-generation-webui is pushing a bunch of new commits right now and the colab is in need of repair

**Comment by markwsac** [comment]
Thanks. Yes the colab is working, I mean it is opening the web app but the responses are not meaningful from the model. See the snapshot. It looks totally different from what they claim. Is it because of some parameters settings? How was your experience about responses from the model? If you check this prompt shown in the image?

<img width="583" alt="image" src="https://user-images.githubusercontent.com/74931612/230214443-3b7c3832-ba9b-4cab-8474-69a5591b972a.png">

**Comment by pcrii** [comment]
i personally think the character file you asked about helps allot. if your still interested i uploaded a different colab thats  allows you to select models and it adds gpt4-x-alpaca. i made it easy to input your own model choice too.  im probably going to maintain the new one and get rid of this one

**Comment by pcrii** [comment]
i think i need to alter the colab-setting.json .its applies this setting ```"chat_generation_attempts": 3,``` that was causing me problems. 
in my previous unshared colab i wouldnt import that json but i wanted to try and preserve what i could from the original. 
you can change it within the webui. but ill try to figure out what setting work best and have them defaulted

**Comment by pcrii** [comment]
![Untitled](https://user-images.githubusercontent.com/1282822/230261307-bf68ce3f-f98e-4b74-a236-5fe3de12528a.png)
loaded up and mine just got weird too but was more verbose about it. and answered the question first.  i definitely recommend setting a character

**Comment by markwsac** [comment]
Thanks for your guidance
